version: '3.8'

services:
  nextcloud:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  api:
    build: .
    restart: always
    ports:
      - 8081:80
      - 8444:443
    depends_on:
      - nextcloud

  db:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  nextcloud-data:
  db-data:
